//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CourseRegistration
{
    public int CourseRegisterID { get; set; }
    public int CourseID { get; set; }
    public string ApplicantName { get; set; }
    public string PhoneNumber { get; set; }
    public string Email { get; set; }
    public Nullable<int> JoinPeopleNumber { get; set; }
    public Nullable<int> JoinPetNumber { get; set; }
    public string RegistrationDate { get; set; }
    public string RegistrationTime { get; set; }

    public virtual GroupCours GroupCours { get; set; }
}

public partial class Employee
{
    public int EmployeeID { get; set; }
    public string EmployeeName { get; set; }
    public string EmployeePwd { get; set; }
    public string Email { get; set; }
    public Nullable<int> PermissionID { get; set; }
    public string StartDate { get; set; }
    public string LeaveDate { get; set; }

    public virtual Permission Permission { get; set; }
    public virtual Trainer Trainer { get; set; }
}

public partial class GroupCours
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GroupCours()
    {
        this.CourseRegistrations = new HashSet<CourseRegistration>();
    }

    public int CourseID { get; set; }
    public string CourseName { get; set; }
    public string Introduction { get; set; }
    public string StartDate { get; set; }
    public string StartTime { get; set; }
    public string EndTime { get; set; }
    public Nullable<int> MaximumPeople { get; set; }
    public Nullable<int> MaximumPet { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CourseRegistration> CourseRegistrations { get; set; }
}

public partial class InquiryForm
{
    public int FormNo { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string Q5 { get; set; }
    public string Q6 { get; set; }
    public string Q7 { get; set; }
    public string Q8 { get; set; }
    public string Q9 { get; set; }
    public string Q10 { get; set; }
    public string Q11 { get; set; }
    public string Q12 { get; set; }
    public string Q13 { get; set; }
    public string Q14 { get; set; }
    public string Q15 { get; set; }
    public string Q16 { get; set; }
    public string Q17 { get; set; }
    public string Q18 { get; set; }
    public string Status { get; set; }
    public string QDate { get; set; }
    public string QTime { get; set; }
    public Nullable<int> EmployeeiD { get; set; }
}

public partial class MallDiscountCode
{
    public int No { get; set; }
    public string DiscountCode { get; set; }
    public Nullable<decimal> NumberOfDiscounts { get; set; }
    public string StartDate { get; set; }
    public string EndDate { get; set; }
}

public partial class MallOrder
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MallOrder()
    {
        this.MallOrdersDetails = new HashSet<MallOrdersDetail>();
    }

    public int OrderNumber { get; set; }
    public int CustomerId { get; set; }
    public string DiscountCode { get; set; }
    public Nullable<int> SubTotal { get; set; }
    public Nullable<int> Total { get; set; }
    public string OrderDate { get; set; }
    public string OrderTime { get; set; }
    public string OrderStatus { get; set; }

    public virtual Member Member { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MallOrdersDetail> MallOrdersDetails { get; set; }
}

public partial class MallOrdersDetail
{
    public int No { get; set; }
    public int OrderNumber { get; set; }
    public Nullable<int> CustomerId { get; set; }
    public string ProductID { get; set; }
    public string ProductName { get; set; }
    public string Spec { get; set; }
    public Nullable<int> UnitPrice { get; set; }
    public Nullable<int> Number { get; set; }
    public Nullable<int> SubTotal { get; set; }
    public string DiscountCode { get; set; }
    public Nullable<int> DiscountAmount { get; set; }
    public Nullable<int> Total { get; set; }
    public string OrderDate { get; set; }
    public string OrderTime { get; set; }
    public string OrderStatus { get; set; }

    public virtual MallOrder MallOrder { get; set; }
    public virtual MallProduct MallProduct { get; set; }
}

public partial class MallProduct
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MallProduct()
    {
        this.MallOrdersDetails = new HashSet<MallOrdersDetail>();
    }

    public string ProductID { get; set; }
    public string Category { get; set; }
    public string ProductName { get; set; }
    public string Description { get; set; }
    public Nullable<int> Price { get; set; }
    public Nullable<int> Stock { get; set; }
    public string ImageUrl { get; set; }
    public string Spec { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MallOrdersDetail> MallOrdersDetails { get; set; }
}

public partial class Member
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Member()
    {
        this.MallOrders = new HashSet<MallOrder>();
        this.Pets = new HashSet<Pet>();
        this.RoomOrders = new HashSet<RoomOrder>();
    }

    public int CustomerId { get; set; }
    public string CustomerName { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Phone { get; set; }
    public string Remark { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MallOrder> MallOrders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Pet> Pets { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RoomOrder> RoomOrders { get; set; }
}

public partial class Permission
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Permission()
    {
        this.Employees = new HashSet<Employee>();
    }

    public int PermissionID { get; set; }
    public string JobTitle { get; set; }
    public string RoomOrderEdit { get; set; }
    public string RoomOrderView { get; set; }
    public string MallOrderEdit { get; set; }
    public string MallOrderView { get; set; }
    public string CourseEdit { get; set; }
    public string CourseView { get; set; }
    public string MemberEdit { get; set; }
    public string MemberView { get; set; }
    public string PermissionEdit { get; set; }
    public string PermissionView { get; set; }
    public string EmployeeEdit { get; set; }
    public string EmployeeView { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Employee> Employees { get; set; }
}

public partial class Pet
{
    public int Id { get; set; }
    public Nullable<int> CustomerId { get; set; }
    public string PetName { get; set; }
    public string PetKind { get; set; }
    public string PetSize { get; set; }
    public string PetImageUrl { get; set; }
    public string Requirement { get; set; }

    public virtual Member Member { get; set; }
}

public partial class Room
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Room()
    {
        this.RoomOrderDetails = new HashSet<RoomOrderDetail>();
    }

    public string RoomType { get; set; }
    public string PetType { get; set; }
    public Nullable<int> Price { get; set; }
    public string Status { get; set; }
    public string RoomImageUrl { get; set; }
    public string RoomHeight { get; set; }
    public string RoomWidth { get; set; }
    public string RoomDepth { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RoomOrderDetail> RoomOrderDetails { get; set; }
}

public partial class RoomOrder
{
    public int RoomOrderId { get; set; }
    public Nullable<int> CustomerId { get; set; }
    public string RoomType { get; set; }
    public Nullable<System.DateTime> CheckIn { get; set; }
    public Nullable<System.DateTime> CheckOut { get; set; }
    public string Total { get; set; }

    public virtual Member Member { get; set; }
}

public partial class RoomOrderDetail
{
    public int RoomOrderId { get; set; }
    public string RoomType { get; set; }
    public string PetName { get; set; }
    public string Requirement { get; set; }

    public virtual Room Room { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Trainer
{
    public int EmployeeID { get; set; }
    public string EmployeeShortName { get; set; }
    public string EmployeeImgUrl { get; set; }
    public string Skill { get; set; }
    public string Subject { get; set; }
    public string WantToSay { get; set; }
    public string Experience { get; set; }

    public virtual Employee Employee { get; set; }
}

public partial class V_CourseRegistrations
{
    public int CourseRegisterID { get; set; }
    public int CourseID { get; set; }
    public string ApplicantName { get; set; }
    public string PhoneNumber { get; set; }
    public string Email { get; set; }
    public Nullable<int> JoinPeopleNumber { get; set; }
    public Nullable<int> JoinPetNumber { get; set; }
    public string CourseName { get; set; }
    public string RegistrationDate { get; set; }
    public string RegistrationTime { get; set; }
}

public partial class V_Employees
{
    public int EmployeeID { get; set; }
    public string EmployeeName { get; set; }
    public string EmployeePwd { get; set; }
    public string Email { get; set; }
    public Nullable<int> PermissionID { get; set; }
    public string StartDate { get; set; }
    public string LeaveDate { get; set; }
}

public partial class V_EmployeeWithJobTitle
{
    public int EmployeeID { get; set; }
    public string EmployeeName { get; set; }
    public string Email { get; set; }
    public Nullable<int> PermissionID { get; set; }
    public string JobTitle { get; set; }
    public string StartDate { get; set; }
    public string LeaveDate { get; set; }
}

public partial class V_EmpTrainer
{
    public int EmployeeID { get; set; }
    public string EmployeeName { get; set; }
}

public partial class V_GroupCourse
{
    public int CourseID { get; set; }
    public string CourseName { get; set; }
    public string Introduction { get; set; }
    public string StartDate { get; set; }
    public string StartTime { get; set; }
    public string EndTime { get; set; }
    public Nullable<int> MaximumPeople { get; set; }
    public Nullable<int> MaximumPet { get; set; }
}

public partial class V_GroupCourseActive
{
    public int CourseID { get; set; }
    public string Introduction { get; set; }
    public string CourseName { get; set; }
    public string StartDate { get; set; }
    public string StartTime { get; set; }
    public string EndTime { get; set; }
    public Nullable<int> MaximumPeople { get; set; }
    public Nullable<int> MaximumPet { get; set; }
    public int JoinPeopleNumber { get; set; }
    public int JoinPetNumber { get; set; }
}

public partial class V_JobTitle
{
    public int PermissionID { get; set; }
    public string JobTitle { get; set; }
}

public partial class V_Members
{
    public int CustomerId { get; set; }
    public string CustomerName { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Phone { get; set; }
    public string Remark { get; set; }
}

public partial class V_Permission
{
    public int PermissionID { get; set; }
    public string JobTitle { get; set; }
    public string RoomOrderEdit { get; set; }
    public string RoomOrderView { get; set; }
    public string MallOrderEdit { get; set; }
    public string MallOrderView { get; set; }
    public string CourseEdit { get; set; }
    public string CourseView { get; set; }
    public string MemberEdit { get; set; }
    public string MemberView { get; set; }
    public string PermissionEdit { get; set; }
    public string PermissionView { get; set; }
    public string EmployeeEdit { get; set; }
    public string EmployeeView { get; set; }
}

public partial class V_Trainer
{
    public int EmployeeID { get; set; }
    public string EmployeeShortName { get; set; }
    public string EmployeeImgUrl { get; set; }
    public string Skill { get; set; }
    public string Subject { get; set; }
    public string WantToSay { get; set; }
    public string Experience { get; set; }
    public string EmployeeName { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
